### ISSUE TITLE
Add a draft orthoprofile

### ISSUE THREAD

**Issue by LinguList** [lexibank/nagarajakhasian#1]
I think the orthography is rather easy to manage. If you add a draft profile `cldfbench lexibank.init_profile --context nagarajakhasian --clts-version=v1.4`, I can look into that, but we'd also see how much is automatically accepted...

**Comment by SimonGreenhill** [comment]
Cool - here it is: https://github.com/lexibank/nagarajakhasian/pull/2

**Comment by CMUgarte** [comment]
This is fixed so I'm closing the issue.
